# Generated by Django 5.0.14 on 2026-09-27 22:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_file_threshold', models.FloatField(default=0.8, help_text='Minimum AI confidence score (0.00 - 1.00) required to auto-file to SharePoint.')),
                ('folder_template', models.CharField(default='/Documents/{company_name}/{document_year}/{category_name}', help_text='Dynamic folder structure in SharePoint.', max_length=255)),
                ('gemini_model', models.CharField(default='gemini-2.5-flash', help_text="Active Gemini model ('gemini-2.5-flash' or 'gemini-2.5-pro').", max_length=60)),
                ('delete_local_on_file', models.BooleanField(default=True, help_text='Delete temporary local file immediately after verified upload to SharePoint.')),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configuration',
            },
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('canonical_name', models.CharField(blank=True, db_index=True, help_text='Normalized lowercase representation used to match near-duplicates automatically.', max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True, help_text='AI-generated or admin summary of what documents belong in this category.')),
                ('color', models.CharField(choices=[('indigo', 'Indigo'), ('emerald', 'Emerald'), ('sky', 'Sky Blue'), ('amber', 'Amber'), ('purple', 'Purple'), ('rose', 'Rose'), ('teal', 'Teal'), ('slate', 'Slate')], default='indigo', help_text='Tailwind badge theme color.', max_length=20)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('document_count', models.PositiveIntegerField(default=0)),
                ('is_hidden', models.BooleanField(default=False, help_text='Hide from filter dropdowns without deleting history.')),
                ('merged_into', models.ForeignKey(blank=True, help_text='If merged into another category, references the primary category.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aliases', to='vault.documentcategory')),
            ],
            options={
                'verbose_name_plural': 'Document categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('temp_file', models.FileField(blank=True, help_text='Transient local copy — deleted once filed to SharePoint.', null=True, upload_to='incoming/%Y/%m/%d/')),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('checksum_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('needs_review', 'Needs review'), ('filed', 'Filed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('company_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('document_date', models.DateField(blank=True, help_text='Detected formal date in the document.', null=True)),
                ('document_year', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('extracted_text_excerpt', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('extracted_entities', models.JSONField(blank=True, default=dict, help_text='Dynamic key-value pairs (invoice_no, total, parties, PO, etc.).')),
                ('ai_raw_response', models.JSONField(blank=True, null=True)),
                ('is_manually_edited', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('sharepoint_folder_path', models.CharField(blank=True, max_length=500)),
                ('sharepoint_item_id', models.CharField(blank=True, max_length=255)),
                ('sharepoint_web_url', models.URLField(blank=True, max_length=1000)),
                ('sharepoint_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='vault.documentcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('uploaded', 'Uploaded'), ('validated', 'Validated'), ('classifying', 'Classifying'), ('classified', 'Classified'), ('filing', 'Filing to SharePoint'), ('filed', 'Filed'), ('reviewed', 'Manually reviewed'), ('retried', 'Retried'), ('failed', 'Failed')], max_length=25)),
                ('message', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, help_text='Step latency in milliseconds.', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Telemetry (e.g. token counts, model name, HTTP codes).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='vault.document')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='vault_docum_status_c78d0d_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['company_name'], name='vault_docum_company_69c40f_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_year'], name='vault_docum_documen_851720_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['created_at'], name='vault_docum_created_5e072d_idx'),
        ),
    ]
