# Generated by Django 5.0.14 on 2026-09-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='temp_file',
            field=models.FileField(blank=True, help_text='Transient local copy — strictly deleted only after successful SharePoint filing.', null=True, upload_to='incoming/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='processinglog',
            name='duration_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processinglog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='folder_template',
            field=models.CharField(default='/Documents/{company_name}/{document_year}/{category_name}', max_length=255),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='gemini_model',
            field=models.CharField(default='gemini-2.5-flash', max_length=60),
        ),
    ]
