# Generated by Django 5.0.14 on 2026-09-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_alter_document_temp_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfiguration',
            name='gemini_model',
            field=models.CharField(default='gemini-3.8-flash', max_length=60),
        ),
    ]
